import {
  Archive,
  Award,
  Bus,
  Calendar,
  CalendarDays,
  CalendarRange,
  CheckCircle,
  Crown,
  Ellipsis,
  Flag,
  Flame,
  Folders,
  Gamepad2,
  Gem,
  Gift,
  HeartPulse,
  House,
  Layers,
  LayoutGrid,
  List,
  ListChecks,
  Mail,
  Milestone,
  Moon,
  Palette,
  Phone,
  Rainbow,
  Receipt,
  Repeat,
  Repeat2,
  Shield,
  Shirt,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Tag,
  Target,
  TrendingUp,
  Trophy,
  Utensils,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  bus: Bus,
  "gamepad-2": Gamepad2,
  house: House,
  phone: Phone,
  "heart-pulse": HeartPulse,
  shirt: Shirt,
  gift: Gift,
  ellipsis: Ellipsis,
  wallet: Wallet,
  flag: Flag,
  sprout: Sprout,
  award: Award,
  shield: Shield,
  crown: Crown,
  flame: Flame,
  trophy: Trophy,
  "trending-up": TrendingUp,
  list: List,
  "list-checks": ListChecks,
  layers: Layers,
  archive: Archive,
  receipt: Receipt,
  palette: Palette,
  rainbow: Rainbow,
  mail: Mail,
  folders: Folders,
  "layout-grid": LayoutGrid,
  "check-circle": CheckCircle,
  target: Target,
  milestone: Milestone,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  "calendar-range": CalendarRange,
  moon: Moon,
  sparkles: Sparkles,
  tag: Tag,
  repeat: Repeat,
  "repeat-2": Repeat2,
  smartphone: Smartphone,
  star: Star,
  gem: Gem,
  zap: Zap,
};

export function CategoryIcon({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? Ellipsis;
  return <Icon className={className} strokeWidth={1.75} />;
}
